### ISSUE TITLE
Why was `if(Is_Expander_Present())` removed from L243 of main.c?

### ISSUE THREAD

**Issue by waldnzwrld** [wir35/marf#11]
Looking at a diff between V1 V2 and V2.5 branches, it seems that 

`if(Is_Expander_Present())` was accidentally removed. 

I opened up a [Pull Request](https://github.com/wir35/marf/pull/10) to resolve this if it was indeed accidental.

**Comment by stevenbarsky** [comment]
Good question. I put it back in and will check the expander when I get back to looking at it. Don't think that's the root problem though...

**Comment by waldnzwrld** [comment]
Agreed the problem is likely larger than this, but it's a start.

**Comment by maxl0rd** [comment]
Obsolete. Resolved in 2.5.
