### ISSUE TITLE
AFG 1 Slope Program Effecting The Main Voltage Output 

### ISSUE THREAD

**Issue by DARKSPARKLER** [wir35/marf#17]
When programming slopes on AFG 1 when using it's internal clock, the output voltage seems to change it's voltage level contrary to where the output voltage level sliders are set and stays at a set voltage. 

If programming a varied sequence of notes for an oscillator, if you program the slope function on all the stages it just keeps playing a set note instead of fluctuating between the different stage values. It only seems to have the problem on AFG 1 and not AFG 2. This problem does not occur when externally clocking AFG 1 through it's start and stop pulse inputs, and the slopes vary normally based on the time settings. 

[Here is a video](https://drive.google.com/file/d/1zI0FeuWBW5G9d0MC6iEfcCAJZhfR9ujI/view?usp=sharing) showing the problem in action, along with a few other "issues" that have come up since loading the new firmware.

**Comment by maxl0rd** [comment]
Confirmed. Two reports that sloped steps aren't working correctly.

**Comment by maxl0rd** [comment]
Fixed by 9b55b41

There was a pair of a misplaced parentheses.
