### ISSUE TITLE
Time Slider "No External Voltage Hack" Not Working

### ISSUE THREAD

**Issue by DARKSPARKLER** [wir35/marf#18]
In the previous MARF firmware you could set the time range source to external, and with no CV sources fed into the external inputs, the time interval sliders would provide voltage based on their position to the time output jack, and not affect the timing of the internal clock. The timing of the clock was then based on the fastest value of the selected time range switch and the time multiplier. 

I found a clip of myself using this hack on the original MARF at EMS in Stockholm, so it is within the canon of original functions: [https://youtu.be/pB86hf1Slz0?t=264](https://youtu.be/pB86hf1Slz0?t=264)

**Comment by maxl0rd** [comment]
The time output is currently wired to whatever the time is set to, so in this case, it's sending the 0v from the cv which isn't connected to anything. I will change this back so that the time output is always exactly the time slider. I think you're correct that this is the original behavior.

**Comment by DARKSPARKLER** [comment]
I'm guessing the same behavior would apply to the main voltage output as well?

**Comment by maxl0rd** [comment]
Fixed by b1fb433
