### ISSUE TITLE
Two issues when using AFG 2 as follower

### ISSUE THREAD

**Issue by norjad** [wir35/marf#21]
Hey everyone,

I installed 2.66 Beta 2 today and encountered two issues. Both when using AFG 2 as follower to AFG 1 (ALL PULSES 1 -> START/STOP 2).

When I switch AFG 2 from STROBE to CONT I hear a slope in AFG 2 and the SLOPE LED of its current step lights up. Switching back to STROBE clears that slope.

That does not happen when I do the same in AFG 1 (so it’s probably related to using AFG 2 as follower). But when I stop AFG 1 by switching it to CONT, AFG 2 is still running (at a quarter of the previous speed).

**Comment by norjad** [comment]
Both issues seem to be resolved in beta 3.

**Comment by maxl0rd** [comment]
Thanks for the report. I'll close it.
