### ISSUE TITLE
Issues when recalling other presets than 1

### ISSUE THREAD

**Issue by norjad** [wir35/marf#22]
Beta 4

I have saved three presets. Recalling preset 1 works flawlessly:
1) Push CLEAR upwards -> LED 1 is lit
2) (No change of preset number needed)
3) Confirm by pushing CLEAR upwards again.

When I try to select a different preset number in step 2) though, it happens quite often that the  step/preset LEDs just runs super fast every time I push the STAGE NO switch, so it's not possible to select preset 2 or 3. A power cycle solves the problem, but then it will happen again sooner or later.

**Comment by maxl0rd** [comment]
Resolved in beta 5 (marf-v2-66-2022-07-13.hex.zip)
