### ISSUE TITLE
AFG 2 as follower does not stop when AFG 1 is stopped

### ISSUE THREAD

**Issue by norjad** [wir35/marf#23]
Beta 4

The second part of issue #21, which I reported as solved, happened again occasionally.

I use AFG 2 as follower to AFG 1 (ALL PULSES 1 -> START/STOP 2).

Sometimes when I stop AFG 1, AFG 2 is still running (at a quarter of the previous speed).

I double checked that ALL PULSES of AFG 1 are not firing when AFG 1 is stopped.

**Comment by maxl0rd** [comment]
I believe this will be addressed in the next set of changes.

**Comment by maxl0rd** [comment]
Resolved in beta 5 (marf-v2-66-2022-07-13.hex.zip)
