### ISSUE TITLE
Preset Mode Lockup

### ISSUE THREAD

**Issue by DARKSPARKLER** [wir35/marf#26]
When loading up a preset, I'm having issues with the display getting locked into the preset loading mode (programmed pulses 1 & 2 LED's alternating) and not being able to start or stop functions on the AFG's for a period of time. 

Here is a video of the issue...
https://www.youtube.com/watch?v=K0N6ONVI-5g

**Comment by waldnzwrld** [comment]
I have the same issue. 

It commonly happens for me if I save or load a preset more than once. 

Was going to report it earlier but I was busy visiting my daughter.

**Comment by maxl0rd** [comment]
Repro-ed and fixed as of 822467ef

**Comment by waldnzwrld** [comment]
Thanks @maxl0rd !!
