### ISSUE TITLE
Programmed Pulses Firing On Consecutive Unprogrammed Stages

### ISSUE THREAD

**Issue by DARKSPARKLER** [wir35/marf#29]
I just came across an issue where pulses are firing on the following stage even if it doesn't have a pulse programmed. For example, if you have pulse output 1 programmed on stages 1 and 5, pulses will fire on stages 1&2, then 5&6. Both AFG's are functioning like this, and both pulse outputs have the same behavior when programmed.

**Comment by maxl0rd** [comment]
I can't repro this one at all. I'd have to see it.

**Comment by norjad** [comment]
I can't replicate this either.

**Comment by DARKSPARKLER** [comment]
Ok weird. I reverted back to an earlier version of the firmware from July that didn't have this issue because I have a show on Thursday and I needed to start practicing for it. I probably won't pull out the MARF to put the new firmware back on there to shoot a video till Friday, so hang tight.

**Comment by DARKSPARKLER** [comment]
I re-uploaded this firmware today and I'm still getting this double pulse issue. Here is a video showing the issue:

https://www.youtube.com/watch?v=Q0vTghlEMw4

**Comment by maxl0rd** [comment]
Thanks, Kyle. 

This one was real. It was tricky to see because the second ghost pulse was only a fraction of a ms and didn't light the led.

Fixed by 9118f63.
