### ISSUE TITLE
Programmed pulse output pins are reversed

### ISSUE THREAD

**Issue by maxl0rd** [wir35/marf#3]
The programmed pulse outputs 1 and 2 are reversed, where programmed pulse 1 will fire from pulse output 2 and vice versa. (This has been commonly fixed by either crossing the resistors or cutting and modifying the traces on the PCB).

From https://www.muffwiggler.com/forum/viewtopic.php?f=19&t=223061

**Comment by stevenbarsky** [comment]
This has been addressed in some versions of the hardware, the 248 board sets from SAModular for example. Roman’s code had a swap in the definition which I corrected. This makes my boards from SAModular work properly. TBD is what to do about boards in the field that are not modified. 2 versions of the firmware or secret handshake on startup to select one of the versions.

**Comment by waldnzwrld** [comment]
> TBD is what to do about boards in the field that are not modified. 2 versions of the firmware or secret handshake on startup to select one of the versions.

I would opt for 2 versions of the firmware. It would be difficult to determine whether someone had cut traces and performed a hw fix, or if they were just living with the inverted pulses. Newer board designs would likely incorporate the fix, and the fix in firmware code is likely small enough that maintaining a second packaged version wouldn't be difficult.

**Comment by stevenbarsky** [comment]
Group consensus was to support the "fixed " hardware from SAmodular and get rid of the reversal in the code .v2.5b3
