### ISSUE TITLE
CV jitter

### ISSUE THREAD

**Issue by maxl0rd** [wir35/marf#5]
"CV Jitter" When using "full range" voltage from the main voltage output for pitch, the tone becomes thin & wiry and the tuning fluctuates. Once you program each stage with "quantize" the tuning stabilizes. See Dave Brown's 248 page for more information on CV Jitter. The "Time" CV output when used for pitch is also jittery.

External Inputs are unusable for pitch. When plugging CV into the External Inputs and sending the voltage output from the MARF to an oscillator (Suzanne Ciani style) the signal is degraded. This must have some relation to the CV Jitter noted above, as the output signal becomes extra noisy, and using "quantize" does not help.

See DB's page: https://modularsynthesis.com/roman/buchla248/248marf.htm

**Comment by waldnzwrld** [comment]
I wonder if the jitter comes from the floating point value calculation. If we narrowed the value down to say 3 or 4 decimal places we might get more consistent results.? 

Just musing on this with a quick glance at the way that quantizing divides by 12 but there is not any sort of limiting to the floating point depth in this case, which could definitely account for a jitter with some variance in the applied voltage and resultant calculation.

**Comment by waldnzwrld** [comment]
Opened https://github.com/wir35/marf/pull/12 as a potential fix

**Comment by maxl0rd** [comment]
Obsoleted by the new smoothing schemes in 2.5 and 2.6
