### ISSUE TITLE
Programmed pulses don't fire when externally clocked

### ISSUE THREAD

**Issue by maxl0rd** [wir35/marf#6]
Programmed Pulses don't fire when clocked externally with stages programmed to "stop." This could be some user error here, but I found the best way to "conventionally" clock the MARF externally is to set each stage with a "stop" function from the Operating Mode section and then put the clocking pulse into the "start" pulse input. That way every pulse from an external source will advance the MARF one step, but unfortunately in this configuration programmed output pulses don't fire when the "stop" function is attached to a stage. I don't see why the pulses shouldn't fire, but if someone could give me a good reason why they don't that would be great, or if a v1 owner could let us know if it works in a similar fashion.

Reported: https://www.muffwiggler.com/forum/viewtopic.php?f=19&t=223061

This _does work_ on my v1.

**Comment by stevenbarsky** [comment]
Fixed and verified v2.5b3
