### ISSUE TITLE
What shall we call this version of MARF firmware?

### ISSUE THREAD

**Issue by stevenbarsky** [wir35/marf#9]
What should we label this version? We can’t call it v2.0.  It has no new features, so v3 isn’t called for. I propose calling it v2.5 because of (hopefully) major bug fixes. That being said we’ll need a new branch, v2.5 created. Thoughts?

**Comment by maxl0rd** [comment]
The Atollic branch is on v2.5. Sounds good to me, to continue development on that branch.

**Comment by stevenbarsky** [comment]
2.5 it is!
